# Generated by Django 5.2.16 on 2026-07-08 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRecordRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('contexts', models.JSONField(blank=True, default=list)),
                ('ground_truth', models.TextField(blank=True)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'evaluation record',
                'verbose_name_plural': 'evaluation records',
                'db_table': 'legal_evaluation_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LawyerRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('success_rate', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'lawyer',
                'verbose_name_plural': 'lawyers',
                'db_table': 'legal_lawyer',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocumentRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('source_uri', models.CharField(blank=True, max_length=1024)),
                ('jurisdiction', models.CharField(db_index=True, default='IR', max_length=32)),
                ('document_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('text', models.TextField(blank=True)),
                ('effective_date', models.CharField(blank=True, max_length=32, null=True)),
                ('publication_date', models.CharField(blank=True, max_length=32, null=True)),
                ('version', models.CharField(blank=True, max_length=64, null=True)),
                ('parser_name', models.CharField(default='unknown', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'legal document',
                'verbose_name_plural': 'legal documents',
                'db_table': 'legal_document',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LegalChunkRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=160, unique=True)),
                ('text', models.TextField()),
                ('book', models.CharField(blank=True, max_length=128, null=True)),
                ('bab', models.CharField(blank=True, max_length=128, null=True)),
                ('fasl', models.CharField(blank=True, max_length=128, null=True)),
                ('mabhas', models.CharField(blank=True, max_length=128, null=True)),
                ('goftar', models.CharField(blank=True, max_length=128, null=True)),
                ('article_number', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('note_number', models.CharField(blank=True, max_length=64, null=True)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(db_column='document_external_id', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='legal_orm.legaldocumentrow', to_field='external_id')),
            ],
            options={
                'verbose_name': 'legal chunk',
                'verbose_name_plural': 'legal chunks',
                'db_table': 'legal_chunk',
                'ordering': ['document_id', 'external_id'],
            },
        ),
    ]
